from pathlib import Path

p=Path('src/app-source.jsx')
s=p.read_text()

def repl(old,new,label):
    global s
    n=s.count(old)
    if n!=1:
        raise SystemExit(f'{label}: expected 1 match, got {n}')
    s=s.replace(old,new,1)

repl('''function lsSet(key,val){\n  try{ localStorage.setItem("rr_"+key,JSON.stringify(val)); return true; }\n  catch(e){ return false; }\n}\n''','''function lsSet(key,val){\n  try{\n    localStorage.setItem("rr_"+key,JSON.stringify(val));\n    scheduleSafetyBackup();\n    return true;\n  }catch(e){ return false; }\n}\n''','lsSet')

repl('''const DB_NAME="rightreader", DB_STORE="books";\nlet dbP=null;\nfunction db(){\n  if(dbP) return dbP;\n  dbP=new Promise((res,rej)=>{\n    const r=indexedDB.open(DB_NAME,1);\n    r.onupgradeneeded=()=>{\n      const d=r.result;\n      if(!d.objectStoreNames.contains(DB_STORE)) d.createObjectStore(DB_STORE,{keyPath:"id"});\n    };\n''','''const DB_NAME="rightreader", DB_STORE="books", DB_BACKUP_STORE="safetyBackups";\nlet dbP=null;\nfunction db(){\n  if(dbP) return dbP;\n  dbP=new Promise((res,rej)=>{\n    const r=indexedDB.open(DB_NAME,2);\n    r.onupgradeneeded=()=>{\n      const d=r.result;\n      if(!d.objectStoreNames.contains(DB_STORE)) d.createObjectStore(DB_STORE,{keyPath:"id"});\n      if(!d.objectStoreNames.contains(DB_BACKUP_STORE)) d.createObjectStore(DB_BACKUP_STORE,{keyPath:"id"});\n    };\n''','db version')

repl('''    t.objectStore(DB_STORE).put(rec);\n    t.oncomplete=()=>res(true); t.onerror=()=>rej(t.error);\n''','''    t.objectStore(DB_STORE).put(rec);\n    t.oncomplete=()=>{ scheduleSafetyBackup(); res(true); }; t.onerror=()=>rej(t.error);\n''','dbPut')

repl('''    t.objectStore(DB_STORE).delete(id);\n    t.oncomplete=()=>res(true); t.onerror=()=>rej(t.error);\n  });\n}\n\n/* Safari clears script-writable storage aggressively.''','''    t.objectStore(DB_STORE).delete(id);\n    t.oncomplete=()=>{ scheduleSafetyBackup(); res(true); }; t.onerror=()=>rej(t.error);\n  });\n}\n\n/* Automatic in-app safety copy. This mirrors all rr_ localStorage state and\n   all EPUB bytes into a second IndexedDB store after changes. It protects\n   against partial writes/corruption and gives us one intact local snapshot.\n   It is NOT the reinstall backup: iPadOS may remove all origin storage when\n   the Home Screen app is deleted, so a separate file saved to Files is still\n   required before removing the app. */\nlet safetyTimer=null, safetyBusy=false, safetyAgain=false;\nfunction rrStorageSnapshot(){\n  const storage={};\n  for(let i=0;i<localStorage.length;i++){\n    const k=localStorage.key(i);\n    if(k&&k.startsWith("rr_")&&k!=="rr_autoBackupAt") storage[k]=localStorage.getItem(k);\n  }\n  return storage;\n}\nasync function dbPutSafety(rec){\n  const d=await db();\n  return new Promise((res,rej)=>{\n    const t=d.transaction(DB_BACKUP_STORE,"readwrite");\n    t.objectStore(DB_BACKUP_STORE).put(rec);\n    t.oncomplete=()=>res(true); t.onerror=()=>rej(t.error);\n  });\n}\nasync function dbGetSafety(){\n  const d=await db();\n  return new Promise((res,rej)=>{\n    const t=d.transaction(DB_BACKUP_STORE,"readonly");\n    const q=t.objectStore(DB_BACKUP_STORE).get("latest");\n    q.onsuccess=()=>res(q.result||null); q.onerror=()=>rej(q.error);\n  });\n}\nasync function writeSafetyBackup(){\n  if(safetyBusy){ safetyAgain=true; return; }\n  safetyBusy=true;\n  try{\n    const saved=Date.now();\n    await dbPutSafety({id:"latest",v:3,saved,storage:rrStorageSnapshot(),books:await dbAll()});\n    try{ localStorage.setItem("rr_autoBackupAt",JSON.stringify(saved)); }catch(e){}\n  }catch(e){}\n  finally{\n    safetyBusy=false;\n    if(safetyAgain){ safetyAgain=false; scheduleSafetyBackup(); }\n  }\n}\nfunction scheduleSafetyBackup(){\n  clearTimeout(safetyTimer);\n  safetyTimer=setTimeout(()=>writeSafetyBackup(),1400);\n}\nasync function restoreLocalSafetyCopy(){\n  try{\n    const snap=await dbGetSafety();\n    if(!snap||!snap.storage) return false;\n    for(const [k,v] of Object.entries(snap.storage))\n      if(k.startsWith("rr_")&&typeof v==="string") localStorage.setItem(k,v);\n    for(const r of snap.books||[]) if(r&&r.id&&r.file) await dbPut(r);\n    return true;\n  }catch(e){ return false; }\n}\n\n/* Safari clears script-writable storage aggressively.''','safety helpers')

repl('''  useEffect(()=>{ const s=document.createElement("style"); s.textContent=CSS;\n    document.head.appendChild(s); askPersist(); },[]);\n''','''  useEffect(()=>{ const s=document.createElement("style"); s.textContent=CSS;\n    document.head.appendChild(s); askPersist(); scheduleSafetyBackup(); },[]);\n''','initial safety backup')

repl('''    async function exportAll(){\n      setMsg("Making full backup …");\n      try{\n        const stored=await dbAll();\n        const bookRows=stored.map(r=>({...r,file:bufferToBase64(r.file)}));\n        const storage={};\n        for(let i=0;i<localStorage.length;i++){\n          const k=localStorage.key(i);\n          if(k&&k.startsWith("rr_")) storage[k]=localStorage.getItem(k);\n        }\n        const blob=new Blob([JSON.stringify({\n          v:2,exported:new Date().toISOString(),storage,books:bookRows\n        })],{type:"application/json"});\n        const a=document.createElement("a");\n        a.href=URL.createObjectURL(blob);\n        a.download="right-reader-full-backup-"+today()+".json";\n        a.click();\n        setTimeout(()=>URL.revokeObjectURL(a.href),4000);\n        setMsg("Full backup created. Keep it private: it contains the API key.");\n      }catch(e){ setMsg("Could not create the full backup."); }\n    }\n''','''    async function exportAll(){\n      setMsg("Preparing full backup …");\n      try{\n        await writeSafetyBackup();\n        const stored=await dbAll();\n        const bookRows=stored.map(r=>({...r,file:bufferToBase64(r.file)}));\n        const storage=rrStorageSnapshot();\n        const name="right-reader-reinstall-backup-"+today()+".rrbackup";\n        const blob=new Blob([JSON.stringify({\n          v:3,exported:new Date().toISOString(),storage,books:bookRows\n        })],{type:"application/json"});\n        const file=new File([blob],name,{type:"application/json"});\n        if(navigator.share&&navigator.canShare&&navigator.canShare({files:[file]})){\n          await navigator.share({title:"Right Reader backup",text:"Save this backup in Files before removing Right Reader from the Home Screen.",files:[file]});\n        }else{\n          const a=document.createElement("a");\n          a.href=URL.createObjectURL(blob); a.download=name; a.click();\n          setTimeout(()=>URL.revokeObjectURL(a.href),4000);\n        }\n        lsSet("externalBackupAt",Date.now());\n        setMsg("Backup ready. Keep the .rrbackup file in Files; it contains the API key and books.");\n      }catch(e){\n        if(e&&e.name==="AbortError") setMsg("Backup cancelled.");\n        else setMsg("Could not create the full backup.");\n      }\n    }\n''','exportAll')

repl('''          if(j.v>=2&&j.storage){\n''','''          if(j.v>=2&&j.storage){\n''','restore version unchanged')

repl('''              <h3>Backup</h3>\n              <button className="btn btn-primary" style={{width:"100%"}} onClick={exportAll}>Create full backup</button>\n              <label className="btn btn-plain" style={{width:"100%",marginTop:8,display:"block",textAlign:"center"}}>\n                Restore\n                <input type="file" accept="application/json,.json" style={{display:"none"}}\n                  onChange={e=>e.target.files[0]&&importAll(e.target.files[0])}/>\n              </label>\n              <div className="hint">\n                This backup contains the books, reading position, saved words, history, settings and API key.\n                Create one before ever removing Right Reader from the Home Screen. Keep the file private.\n              </div>\n''','''              <h3>Backup</h3>\n              <button className="btn btn-primary" style={{width:"100%"}} onClick={exportAll}>Save full backup to Files</button>\n              <button className="btn btn-plain" style={{width:"100%",marginTop:8}} onClick={async()=>{\n                if(await restoreLocalSafetyCopy()){ setMsg("Local safety copy restored. Reloading …"); setTimeout(()=>location.reload(),350); }\n                else setMsg("No local safety copy was found.");\n              }}>Restore automatic local copy</button>\n              <label className="btn btn-plain" style={{width:"100%",marginTop:8,display:"block",textAlign:"center"}}>\n                Restore backup file\n                <input type="file" accept="application/json,.json,.rrbackup" style={{display:"none"}}\n                  onChange={e=>e.target.files[0]&&importAll(e.target.files[0])}/>\n              </label>\n              <div className="hint">\n                Right Reader now keeps a full automatic local safety copy after changes. It includes books,\n                reading position, saved words, history, settings and the API key. <b>Important:</b> iPadOS may\n                delete that local copy when the Home Screen app itself is removed. Before removing/re-adding\n                Right Reader, tap <b>Save full backup to Files</b> and choose Save to Files. Keep it private.\n              </div>\n''','backup UI')

# bump SW cache
sw=Path('sw.js')
t=sw.read_text()
if 'const VERSION = "rr-v8";' not in t: raise SystemExit('unexpected sw version')
sw.write_text(t.replace('const VERSION = "rr-v8";','const VERSION = "rr-v9";',1))

# docs
r=Path('README.md')
text=r.read_text()
text=text.replace('Current service-worker cache for this release: `rr-v8`.','Current service-worker cache for this release: `rr-v9`.')
text += '\n\n### Backup safety\n\nRight Reader automatically mirrors all app state and EPUB bytes into a local IndexedDB safety snapshot after changes. Parent → Settings → Backup can also save a complete `.rrbackup` file through the iOS share sheet; before deleting/re-adding the Home Screen app, save that file to Files because iPadOS may delete the app’s own local storage when the installed web app is removed.\n'
r.write_text(text)

p.write_text(s)
print('automatic backup patch applied')
